### PR TITLE
Fix bad slugs

### LINKED ISSUE #62: Identical repo slug issue
@KTS915 @xxsimoxx So I ran a test using Shortcodes Everywhere plugin as an example and we may have a problem.

Original:
- Repo: `https://github.com/xxsimoxx/codepotent-shortcodes-everywhere/`
- Download URL: `https://github.com/xxsimoxx/codepotent-shortcodes-everywhere/releases/download/1.1.2/codepotent-shortcodes-everywhere-1.1.2.zip`
- Slug: `codepotent-shortcodes-everywhere`

Duplicate submitted by me:
- Repo: `https://github.com/viktorix/codepotent-shortcodes-everywhere/`
- Download URL: `https://github.com/viktorix/codepotent-shortcodes-everywhere/releases/download/1.1.2/codepotent-shortcodes-everywhere-1.1.2.zip`
- Slug: `codepotent-shortcodes-everywhere-1.1.2`

As you can see, the directory generated a slug based on the zip file name which includes the version number with periods.

Can we generate our own slug using org and repo slug? For example, my duplicate plugin `viktorix/codepotent-shortcodes-everywhere` would be `viktorix-codepotent-shortcodes-everywhere`.

In addition, since my duplicate plugin's name is also Shortcodes Everywhere, the CPT slug is `shortcodes-everywhere-2`. That -2 isn't going to look good. This touches on issue #36. I think we need to improve the slug generation for CPTs too. What if we used API slug from above for CPT slug too? Save us any future trouble. Or even append it with CPT ID or random numbers.

Instead of:
`https://staging-directory.classicpress.net/plugins/shortcodes-everywhere-2/`

It would be: 
`https://staging-directory.classicpress.net/plugins/viktorix-shortcodes-everywhere/`

You can see meta data for my duplicate plugin here:
https://staging-directory.classicpress.net/wp-admin/post.php?post=2013&action=edit

### PR DESCRIPTION
**Pull request by xxsimoxx**
This PR introduces validation of the slug against this regex `/^[a-zA-Z0-9_\-]+$/` as discussed [here](https://github.com/ClassicPress/Directory/issues/62).

Documentation should be updated to explain this.

Closes #62 .

### CODE REVIEW

File: wp-content/mu-plugins/software-submit-form.php [hunk 1]
```diff
@@ -168,6 +168,9 @@ function kts_render_software_submit_form() {
 			elseif ( $_GET['notification'] === 'not-sent' ) {
 				echo '<div class="alert error-message" role="alert"><p>' . __( 'There was a problem submitting the form. Your message has not been sent.', 'classicpress' ) . '</p></div>';
 			}
+			elseif ( $_GET['notification'] === 'bad_slug' ) {
```
Comment (viktorix) [inline wp-content/mu-plugins/software-submit-form.php]: Should this be `bad-slug`? Based on the redirect code:
`wp_safe_redirect( esc_url_raw( $referer . '?notification=bad-slug' ) );`

**Review by viktorix — CHANGES_REQUESTED** [review]
See my inline comment about the `notification` parameter.

File: wp-content/mu-plugins/software-submit-form.php (hunk 1 above)
Comment (xxsimoxx) [reply wp-content/mu-plugins/software-submit-form.php]: Fixed now. Thank you!

**Review by viktorix — APPROVED** [review]
Looks good.
